- match: '(<)([a-zA-Z0-9:]++)(?=[^>]*></\2>)'
  captures:
    1: punctuation.definition.tag.begin.html
    2: entity.name.tag.html
  push:
    - meta_scope: meta.tag.any.html
    - match: (>)(<)(/)(\2)(>)
      captures:
        1: punctuation.definition.tag.end.html
        2: punctuation.definition.tag.begin.html meta.scope.between-tag-pair.html
        3: punctuation.definition.tag.begin.html
        4: entity.name.tag.html
        5: punctuation.definition.tag.end.html
      pop: true
    - include: tag-stuff
- match: (<\?)(xml)
  captures:
    1: punctuation.definition.tag.html
    2: entity.name.tag.xml.html
  push:
    - meta_scope: meta.tag.preprocessor.xml.html
    - match: (\?>)
      captures:
        1: punctuation.definition.tag.html
        2: entity.name.tag.xml.html
      pop: true
    - include: generic-attr
    - include: double-quoted
    - include: single-quoted
- match: <!--
  captures:
    0: punctuation.definition.comment.html
  push:
    - meta_scope: comment.block.html
    - match: '--\s*>'
      captures:
        0: punctuation.definition.comment.html
      pop: true
    - match: "--"
      scope: invalid.illegal.bad-comments-or-CDATA.html
    - include: embedded
- match: (<!)
  captures:
    0: punctuation.definition.tag.html
  push:
    - meta_scope: meta.tag.sgml.html
    - match: (>)
      captures:
        0: punctuation.definition.tag.html
      pop: true
    - match: (?i:DOCTYPE)
      captures:
        1: entity.name.tag.doctype.html
      push:
        - meta_scope: meta.tag.sgml.doctype.html
        - match: (?=>)
          captures:
            1: entity.name.tag.doctype.html
          pop: true
        - match: ("[^">]*")
          scope: string.quoted.double.doctype.identifiers-and-DTDs.html
    - match: '\[CDATA\['
      push:
        - meta_scope: constant.other.inline-data.html
        - match: "]](?=>)"
          pop: true
    - match: (\s*)(?!--|>)\S(\s*)
      scope: invalid.illegal.bad-comments-or-CDATA.html
- include: embedded
- match: '(?:^\s+)?(<)((?i:style))\b(?![^>]*/>)'
  captures:
    1: punctuation.definition.tag.begin.html
    2: entity.name.tag.style.html
  push:
    - match: (?i)(</)(style)(>)
      captures:
        1: punctuation.definition.tag.begin.html
        2: entity.name.tag.style.html
        3: punctuation.definition.tag.end.html
      pop: true
    - include: tag-stuff
    - match: (>)
      scope: punctuation.definition.tag.end.html
      push:
        - meta_content_scope: source.css.embedded.html
        - include: embedded-code
        - include: 'scope:source.css'
      with_prototype:
        - match: (?i)(?=</style)
          pop: true
- match: '(<)((?i:script))\b(?![^>]*/>)(?![^>]*(?i:type.?=.?text/((?!javascript).*)))'
  captures:
    1: punctuation.definition.tag.begin.html
    2: entity.name.tag.script.html
  push:
    - match: (?i)(</)(script)(>)
      captures:
        1: punctuation.definition.tag.begin.html
        2: entity.name.tag.script.html
        3: punctuation.definition.tag.end.html
      pop: true
    - include: tag-stuff
    - match: (>)
      scope: punctuation.definition.tag.end.html
      push:
        - meta_content_scope: source.js.embedded.html
        - include: embedded-code
        - include: 'scope:source.js'
      with_prototype:
         - match: (?i)(?=</script)
           pop: true
- match: (</?)((?i:body|head|html)\b)
  captures:
    1: punctuation.definition.tag.begin.html
    2: entity.name.tag.structure.any.html
  push:
    - meta_scope: meta.tag.structure.any.html
    - match: (>)
      scope: punctuation.definition.tag.end.html
      pop: true
    - include: tag-stuff
- match: (</?)((?i:address|blockquote|dd|div|dl|dt|fieldset|form|frame|frameset|h1|h2|h3|h4|h5|h6|iframe|noframes|object|ol|p|ul|applet|center|dir|hr|menu|pre)\b)
  captures:
    1: punctuation.definition.tag.begin.html
    2: entity.name.tag.block.any.html
  push:
    - meta_scope: meta.tag.block.any.html
    - match: (>)
      captures:
        1: punctuation.definition.tag.end.html
      pop: true
    - include: tag-stuff
- match: (</?)((?i:a|abbr|acronym|area|b|base|basefont|bdo|big|br|button|caption|cite|code|col|colgroup|del|dfn|em|font|head|html|i|img|input|ins|isindex|kbd|label|legend|li|link|map|meta|noscript|optgroup|option|param|q|s|samp|script|select|small|span|strike|strong|style|sub|sup|table|tbody|td|textarea|tfoot|th|thead|title|tr|tt|u|var)\b)
  captures:
    1: punctuation.definition.tag.begin.html
    2: entity.name.tag.inline.any.html
  push:
    - meta_scope: meta.tag.inline.any.html
    - match: "((?: ?/)?>)"
      captures:
        1: punctuation.definition.tag.end.html
      pop: true
    - include: tag-stuff
- match: "(</?)([a-zA-Z0-9:]+)"
  captures:
    1: punctuation.definition.tag.begin.html
    2: entity.name.tag.other.html
  push:
    - meta_scope: meta.tag.other.html
    - match: (>)
      captures:
        1: punctuation.definition.tag.end.html
      pop: true
    - include: tag-stuff
- include: entities
- match: (<>)
  scope: invalid.illegal.incomplete.html
- match: (<)
  scope: invalid.illegal.bad-angle-bracket.html